[phases.setup]
nixPkgs = ["php82", "nodejs-18_x"]

[phases.install]
cmds = [
  "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\"",
  "php composer-setup.php --install-dir=/usr/local/bin --filename=composer",
  "php -r \"unlink('composer-setup.php');\"",
  "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist",
  "npm ci",
  "npm run build"
]

[phases.build]
cmds = [
  "composer run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
