#!/bin/bash

# Script to check EC2 instance status
# Run this to see what's actually running on your server

echo "=== EC2 Instance Status Check ==="
echo "Target: 13.211.143.224"
echo ""

echo "To check your EC2 instance status, run these commands:"
echo ""
echo "1. SSH into your instance:"
echo "   ssh -i your-key.pem ubuntu@13.211.143.224"
echo ""
echo "2. Check if Docker is running:"
echo "   sudo systemctl status docker"
echo ""
echo "3. Check running containers:"
echo "   docker ps -a"
echo ""
echo "4. Check container logs:"
echo "   docker logs davids-wood-furniture"
echo ""
echo "5. Check if Apache is running:"
echo "   sudo systemctl status apache2"
echo ""
echo "6. Check what's listening on ports:"
echo "   sudo netstat -tlnp | grep -E ':(80|8080)'"
echo ""
echo "7. Test local connection:"
echo "   curl -v http://localhost:8080/test.php"
echo "   curl -v http://localhost:80/test.php"
echo ""
echo "8. Check Apache error logs:"
echo "   sudo tail -20 /var/log/apache2/error.log"
echo ""
echo "=== Quick Fixes ==="
echo ""
echo "If container is not running:"
echo "   docker start davids-wood-furniture"
echo ""
echo "If container is running but not responding:"
echo "   docker restart davids-wood-furniture"
echo ""
echo "If Apache is not running:"
echo "   sudo systemctl start apache2"
echo "   sudo systemctl enable apache2"
echo ""
echo "If you need to rebuild the container:"
echo "   docker rm -f davids-wood-furniture"
echo "   # Then redeploy from GitHub Actions"
