name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: davids_wood_test
        ports: [3306:3306]
      redis:
        image: redis:7-alpine
        ports: [6379:6379]

    strategy:
      matrix:
        php-version: [8.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, redis

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Install MySQL Client
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client
        
    - name: Wait for MySQL
      run: sleep 15
        
    - name: Create Test Database
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        mysql -h127.0.0.1 -P3306 -uroot -p$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS davids_wood_test;"
        mysql -h127.0.0.1 -P3306 -uroot -p$DB_PASSWORD -e "CREATE USER IF NOT EXISTS 'davidswood_user'@'%' IDENTIFIED BY 'StrongPass123!';"
        mysql -h127.0.0.1 -P3306 -uroot -p$DB_PASSWORD -e "GRANT ALL PRIVILEGES ON davids_wood_test.* TO 'davidswood_user'@'%';"
        mysql -h127.0.0.1 -P3306 -uroot -p$DB_PASSWORD -e "FLUSH PRIVILEGES;"

    - name: Run tests
      env:
        DB_PASSWORD: StrongPass123!
        DB_CONNECTION: mysql
        DB_DATABASE: davids_wood_test
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USERNAME: davidswood_user
      run: php artisan test

  code-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick, redis

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run Laravel Pint (Code Style)
      run: ./vendor/bin/pint --test

  frontend-build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build assets
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: public/build/