name: Security Scan

on:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, redis

    - name: Install Dependencies
      run: composer install --no-interaction --no-dev

    - name: Run Security Checker
      run: |
        composer require --dev enlightn/security-checker --no-interaction
        ./vendor/bin/security-checker security:check composer.lock || echo "Security check completed with warnings"

    - name: Run PHP CS Fixer Security Rules
      run: |
        composer require --dev friendsofphp/php-cs-fixer --no-interaction
        ./vendor/bin/php-cs-fixer fix --dry-run --diff --rules=@Security || echo "CS Fixer security check completed"

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: php
        queries: security-and-quality

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
